---
- name: Install dependencies for {{ ansible_os_family }}
  yum:
    name: '{{ item }}'
    state: installed
    update_cache: yes
  with_items:
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - xz 
      - xz-devel
  become: true

