---
- name: Install dependencies for Red Hat family
  yum:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items:
      - git
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - xz
      - xz-devel
  become: true

