---
- name: Check for previous installation of pyenv
  stat:
    path: '{{ pyenv.path }}/bin/pyenv'
  ignore_errors: true
  register: pyenv_bin_dir

- block:
  - name: Create base directory
    file:
      path: '{{ pyenv.path }}'
      state: directory
      group: '{{ ansible_user }}'
      owner: '{{ ansible_user }}'
    become: true

  - name: Clone pyenv
    git:
      repo: '{{ pyenv.repo }}'
      dest: '{{ pyenv.path }}'
      accept_hostkey: yes

  - name: Compile dynamic bash extension to speed up pyenv
    raw: '{{ pyenv.path }}/src/configure && make -C {{ pyenv.path }}/src'

  - name: Add pyenv to PATH
    template:
      src: pyenv.sh.j2
      dest: /etc/profile.d/pyenv.sh
      owner: root
      group: root
      mode: 0775
    become: true
  when: pyenv_bin_dir.stat.exists == false
