---
- import_tasks: dependencies/apt.yml
  when: ansible_os_family == 'Debian'

- import_tasks: dependencies/yum.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: install-pyenv.yml

- name: Install plugins
  include_tasks: install-plugin.yml
  with_items:
    - '{{ pyenv.plugins }}'

- name: Install pythons
  include_tasks: install-python.yml
  with_items:
    - '{{ pythons }}'
