---
- import_tasks: dependencies/apt.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- import_tasks: dependencies/yum.yml
  when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon" or ansible_distribution == 'Red Hat Enterprise Linux'

- import_tasks: install-pyenv.yml

- name: Install plugins
  include_tasks: install-plugin.yml
  with_items:
    - '{{ pyenv.plugins }}'

- name: Install pythons
  include_tasks: install-python.yml
  with_items:
    - '{{ pythons }}'
