---
- name: Initial setup
  hosts: vagrant
  gather_facts: no

  roles:
    - { role: ../ansible-role-pyenv/vagrant/initial }

- name: Role test [pyenv] < pyenv_env = local >
  hosts: vagrant
  vars:
    - pyenv_env: local
  roles:
    - { role: ../ansible-role-pyenv }

- name: Role test [pyenv] < pyenv_env = system >
  hosts: vagrant
  vars:
    - pyenv_env: system
  roles:
    - { role: ../ansible-role-pyenv }
