---
- name: Determine distribution type
  raw: |
    if [[ -e /etc/os-release ]]; then
      awk -F"[='\"]+" '/^ID_LIKE/{print $2}' /etc/os-release
    elif [[ -e /etc/redhat-release ]]; then
      echo "rhel"
    else
      echo "unknown"
    fi
  register: release_like
  changed_when: false
  failed_when: release_like.stdout|length < 1 or "unknown" in release_like.stdout
  ignore_errors: yes

- block:
  - name: Install dependencies [centos/rhel]
    raw: yum -y update && yum -y install python libselinux-python
    become: true

  - name: Cleanup yum
    raw: yum -y clean packages
    become: true

  when: release_like.stdout is search("rhel")

- block:
  - name: Install dependencies [ubuntu/debian]
    raw: apt-get -y update && apt-get install -y python-simplejson
    become: true

  - name: Cleanup apt
    raw: apt-get -y autoremove && apt-get -y autoclean
    become: true

  when: release_like.stdout is search("debian")
